### ISSUE TITLE
Reject all Cookies Button

### ISSUE THREAD

**Issue by petereberlecom** [brainsum/cookieconsent#140]
Hi, is there a way to reject all cookies, similar as accept all cookies?

I couldn't find it in the settings object

cheers

**Comment by MontiMarco92** [comment]
Hi @petereberlecom . Yes there is a `showRejectAllButton` setting you can add to the config object and set it to `true`:

```
window.CookieConsent.init({
    modalMainTextMoreLink: null,
    UITimeout: 1000,
    // Show the 'reject all cookies' button. It's false by default.
    showRejectAllButton: true,
    ... // rest of config
})
```

![Screenshot from 2024-07-17 08-45-01](https://github.com/user-attachments/assets/e1707954-2c4d-4ff1-9b98-2949524141b5)

I'm going to update the Readme so it's clear this option exists.

Hope this helps.

Cheers!
