### ISSUE TITLE
Consent as dialog box?

### ISSUE THREAD

**Issue by AreSee** [brainsum/cookieconsent#50]
How to display the consent as a dialog box so the user has to make a choice?

**Comment by ChartsWatcher** [comment]
I am wondering the same. Is there some method we can call? (Great consent tool by the way, exactly what I needed!)

**Comment by MontiMarco92** [comment]
You can now set `mode` option to 'modal' on the config object, and you will see the consent settings as a dialog:

```
window.CookieConsent.init({
    // Show 'bar' or 'modal' initial layout
    mode: 'bar'
    // ...rest of the config
})
```
![Screenshot from 2024-07-17 09-26-45](https://github.com/user-attachments/assets/dba01c45-1dcb-434b-bb0d-366eb53f84fa)
