### ISSUE TITLE
Which license ... ISC or GPL ...?

### ISSUE THREAD

**Issue by nfreear** [brainsum/cookieconsent#55]
Hi,

Thanks for the library.

I'm confused -- `package.json` says `ISC`; `LICENSE` says `GPL`.

Please can you settle on one license, and make these two files match?

You won't get much usage or many contributions until the license is settled!

 * https://github.com/brainsum/cookieconsent/blob/master/package.json#L20;
 * https://github.com/brainsum/cookieconsent/blob/master/LICENSE;

Relates to :~ #3;

Btw, a more permissive license, e.g. MIT, ISC etc. is common for libraries, while `GPL` is often applied to complete applications - WordPress, Moodle etc.

Thank you,

Nick

**Comment by pedro-p** [comment]
Hi,

The license has been updated to ISC.
We hope this will help this library thrive.

**Comment by nfreear** [comment]
Thank Peter / @pedro-p ... much appreciated!

* https://github.com/brainsum/cookieconsent/commit/70772003f48ae1f221ce1f7f62fbeb702dc5d935;

Yours,

Nick
