### ISSUE TITLE
Add "Reject All" option

### ISSUE THREAD

**Issue by NathanBnm** [brainsum/cookieconsent#59]
Since March 31 it's necessary to have an "Reject all" option to be in compliance with the GDPR.

I noticed that it was implemented in #49 which has been closed, any possibility to add this feature?

**Comment by berwiecom** [comment]
Good to know in general @NathanBnm. Can you provide a source link?

**Comment by NathanBnm** [comment]
I did not find the official source but the regulation applies in France. Anyway the addition of such a feature would be convenient.

In French (https://www.cnil.fr/fr/nouvelles-regles-cookies-et-autres-traceurs-bilan-accompagnement-cnil-actions-a-venir)

You can also check the officiale GDPR website here : https://gdpr.eu/

**Comment by berwiecom** [comment]
Well, a non-deep-link like gdpr.eu that lets others search for your mentioned "compliance with the GDPR" might have led to the not reopened issue #59. Great resource though :)

**Comment by tdrzewosz** [comment]
Hello, I need this feature, please. thanks. kind regards

**Comment by p-w** [comment]
Unfortunately this is a major requirement for most European, but definitely UK and DE based websites.

More can be found here [from the Information Commissioner's Office (UK)](https://ico.org.uk/for-organisations/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/how-do-we-comply-with-the-cookie-rules/#comply13)

**Comment by MarcNitsche** [comment]
Does anyone have a solution now?

**Comment by bouskdav** [comment]
Created a PR ( #81 )

**Comment by bouskdav** [comment]
> Created a PR ( #81 )

funny.. now i look to #49 and the change looks almost the same.

**Comment by chriszuercher** [comment]
Could the PR be merged? We also need this functionality.

**Comment by MontiMarco92** [comment]
there is a `showRejectAllButton` setting you can add to the config object and set it to true:
```
window.CookieConsent.init({
    modalMainTextMoreLink: null,
    UITimeout: 1000,
    // Show the 'reject all cookies' button. It's false by default.
    showRejectAllButton: true,
    ... // rest of config
})
```
