### ISSUE TITLE
Google AdSense _glc_au cookie not blocked

### ISSUE THREAD

**Issue by mado-opus** [brainsum/cookieconsent#94]
Hi all,
Using `adsense: { category: "<category name>", type: "script-tag", cookies: [ {name: "_gcl_au", domain: '<domain name>'} ], language: {locale: {en: {name: "Google Adsense"}}} },` as one of the services I still see the cookie `_gcl_au` popping up when it is supposed to be blocked.

The following scripts are used to generate this cookie:
```
 <script id="googleTagManager2" async src="https://www.googletagmanager.com/gtag/js?id=<ID>">
 </script>
 
 <script id="googleTagManager">
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());
         gtag('config', '<ID>);
 </script>
```

Does anyone might have an idea what I am doing wrong?

**Comment by mado-opus** [comment]
I had to add the script tag `type="text/plain"` :-).

**Comment by Scippy** [comment]
Where you've added type="text/plain"?

**Comment by Scippy** [comment]
> I had to add the script tag `type="text/plain"` :-).

Where you've added type="text/plain"?

**Comment by mado-opus** [comment]
It's a javascript tag that you can add above the script you're trying to block:
`<script type="text/plain">
    // script
</script>
`
